---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/bosh/bosh-ecosystem-concourse
    tag: latest

inputs:
  - name: telemetry-release
  - name: bosh-cli-github-release
  - name: ruby-release
  - name: ci

outputs:
  - name: telemetry-release

run:
  path: ci/ci/tasks/bump-ruby-package.sh

params:
  GCS_SERVICE_ACCOUNT_KEY:
  GITHUB_NAME:
  GITHUB_EMAIL:
