---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/ubuntu
    tag: xenial

inputs:
- name: telemetry-release
- name: bosh-cli-github-release
- name: version
- name: ci

outputs:
- name: release-tarball

run:
  path: ci/ci/tasks/create-release.sh
