---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: tpi-docker-virtual.usw1.packages.broadcom.com/library/ubuntu
    tag: jammy
    username: ((jfrog-artifactory.jfrog-username))
    password: ((jfrog-artifactory.jfrog-password))

inputs:
- name: telemetry-release
- name: bosh-cli-github-release
- name: version
- name: ci
- name: bbl-cli-github-release

outputs:
- name: release-tarball

run:
  path: ci/ci/tasks/create-release.sh
