---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/ubuntu
    tag: jammy

inputs:
- name: stemcell
- name: bpm-release
- name: version
- name: bosh-cli-github-release
- name: telemetry-release
- name: ci
- name: release-tarball
- name: testbed-lease
  optional: true
- name: smith
- name: om

run:
  path: ci/ci/tasks/deploy-telemetry.sh

params:
  CENTRALIZER_DEPLOYMENT_NAME:
  AGENT_DEPLOYMENT_NAME:
  AUDIT_MODE:
  LOADER_API_KEY:
  LOADER_ENDPOINT:
  ENV_TYPE:
  IAAS_TYPE:
  FOUNDATION_ID:
  FOUNDATION_NICKNAME:
  FLUSH_INTERVAL:
  COLLECTOR_CRON_SCHEDULE:
  OPSMANAGER_HOSTNAME:
  OPSMANAGER_CLIENT_NAME:
  OPSMANAGER_CLIENT_SECRET:
  OPSMANAGER_INSECURE_SKIP_TLS_VERIFY:
  CF_API_URL:
  USAGE_SERVICE_URL:
  USAGE_SERVICE_CLIENT_ID:
  USAGE_SERVICE_CLIENT_SECRET:
  USAGE_SERVICE_INSECURE_SKIP_TLS_VERIFY:
  SHEPHERD_SECRET:
  TOOLSMITHS_ENV:
  DATA_COLLECTION_MULTI_SELECT_OPTIONS:
  OPERATIONAL_DATA_ONLY:
