---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/golang
    tag: 1.20.2

inputs:
  - name: telemetry-release
  - name: ci

run:
  path: ci/ci/tasks/run-telemetry-receiver-tests.sh
