---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: tpi-docker-virtual.usw1.packages.broadcom.com/library/golang
    tag: 1.24.2
    username: ((jfrog-artifactory.jfrog-username))
    password: ((jfrog-artifactory.jfrog-password))

inputs:
  - name: telemetry-release
  - name: ci

run:
  path: ci/ci/tasks/run-telemetry-receiver-tests.sh
