---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/ruby
    tag: 3.2.2

inputs:
  - name: bosh-cli-github-release
  - name: telemetry-release
  - name: ci
  - name: version
  - name: smith
  - name: testbed-lease
  - name: om

run:
  path: ci/ci/tasks/test-acceptance-sends-to-centralizer.sh

params:
  LOADER_URL:
  LOADER_API_KEY:
  CENTRALIZER_BOSH_DEPLOYMENT:
  AGENT_BOSH_DEPLOYMENT:
  AGENT_BOSH_INSTANCE:
  EXPECTED_ENV_TYPE:
  EXPECTED_FOUNDATION_NICKNAME:
  EXPECTED_IAAS_TYPE:
  EXPECTED_FOUNDATION_ID:
  AUDIT_MODE:
  TOOLSMITHS_ENV:
  SHEPHERD_SECRET:
