---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/ruby
    tag: sha256:091ee4779c0d90155b6d1a317855ce64714e6485f9db4413c812ddd112df7dc7

inputs:
  - name: bbl-state
  - name: bosh-cli-github-release
  - name: bbl-cli-github-release
  - name: telemetry-release
  - name: ci

run:
  path: ci/ci/tasks/test-acceptance-sends-to-centralizer.sh

params:
  LOADER_URL:
  LOADER_API_KEY:
  CENTRALIZER_BOSH_DEPLOYMENT:
  AGENT_BOSH_DEPLOYMENT:
  AGENT_BOSH_INSTANCE:
  EXPECTED_ENV_TYPE:
  EXPECTED_FOUNDATION_NICKNAME:
  EXPECTED_IAAS_TYPE:
  EXPECTED_FOUNDATION_ID:
  AUDIT_MODE:
