---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: tpi-docker-virtual.usw1.packages.broadcom.com/library/ubuntu
    tag: jammy
    username: ((jfrog-artifactory.jfrog-username))
    password: ((jfrog-artifactory.jfrog-password))

inputs:
  - name: telemetry-release
  - name: bosh-cli-github-release
  - name: pivotal-telemetry-collector
  - name: ci
  - name: bbl-cli-github-release

outputs:
  - name: telemetry-release

run:
  path: ci/ci/tasks/update-release-package.sh

params:
  GCS_SERVICE_ACCOUNT_KEY:
  GITHUB_NAME:
  GITHUB_EMAIL:
