resource_types:
- name: bbl-state-resource
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cfinfrastructure/bbl-state-resource
- name: bosh-deployment
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cloudfoundry/bosh-deployment-resource
- name: pivnet
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/pivotalcf/pivnet-resource
    tag: latest-final
- name: github-release
  type: registry-image
  source: {repository: harbor-repo.vmware.com/dockerhub-proxy-cache/concourse/github-release-resource}
- name: pcf-pool
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cftoolsmiths/toolsmiths-envs-resource

resources:
- name: bosh-cli-github-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: bosh-cli
    release: true
    access_token: ((github.pivotal-cf-access-token))
- name: smith-cli-github-release
  type: github-release
  version:
    tag: 'v2.3.0'
  source:
    owner: pivotal
    repository: smith
    access_token: ((github.pivotal-cf-access-token))
- name: om-cli-github-release
  type: github-release
  source:
    owner: pivotal-cf
    repository: om
    access_token: ((github.pivotal-cf-access-token))
- name: telemetry-receiver-app
  type: cf
  source:
    api: ((service-accounts/pcf1-deploy.api-url))
    username: ((service-accounts/pcf1-deploy.username))
    password: ((service-accounts/pcf1-deploy.password))
    organization: ((service-accounts/pcf1-deploy.org))
    space: stage
- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-((stemcell-version))-go_agent
- name: bpm-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bpm-release
- name: telemetry-release
  type: git
  source:
    branch: ((branch))
    uri: git@github.com:pivotal-cf/telemetry-release
    private_key: ((github.telemetry-release-git-deploy-private-key))
    ignore_paths:
    - ci
- name: ci
  type: git
  source:
    branch: main
    uri: git@github.com:pivotal-cf/telemetry-release
    private_key: ((github.telemetry-release-git-deploy-private-key))
    paths:
    - ci
    - src
- name: telemetry-receiver-source
  type: git
  source:
    branch: ((branch))
    uri: git@github.com:pivotal-cf/telemetry-release
    paths:
    - src/acceptance_tests/telemetry_receiver
    - ci/tasks/run-telemetry-receiver-tests.*
    private_key: ((github.telemetry-release-git-deploy-private-key))
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:pivotal-cf/telemetry-release
    branch: ((branch))
    file: ci/VERSION
    private_key: ((github.telemetry-release-git-deploy-private-key))
- name: env-pool
  type: pcf-pool
  source:
    api_token: ((toolsmiths/auth.api-token))
    hostname: environments.toolsmiths.cf-app.com
    pool_name: ((tas-version))

- name: pivotal-telemetry-collector
  type: pivnet
  source:
    api_token: ((pivnet.api-token))
    product_slug: pivotal-telemetry-collector
    copy_metadata: true
    product_version: ((telemetry-collector-regex))
- name: ruby-release
  type: git
  source:
    branch: main
    uri: git@github.com:cloudfoundry/bosh-package-ruby-release.git
    private_key: ((github.telemetry-release-git-deploy-private-key))

jobs:
- name: update-ruby
  plan:
    - in_parallel:
      - get: telemetry-release
      - get: ruby-release
        trigger: true
      - get: ci
      - get: bosh-cli-github-release
        params:
          globs:
          - bosh-cli-*-linux-amd64
    - task: bump-ruby-package
      file: ci/ci/tasks/bump-ruby-package.yml
      params:
        GCS_SERVICE_ACCOUNT_KEY: ((service-accounts/gcp.ci-gcs-service-account-key))
        GITHUB_NAME: ((telemetry-release-repo.github-name))
        GITHUB_EMAIL: ((telemetry-release-repo.github-email))
    - put: telemetry-release
      params:
        repository: telemetry-release
        rebase: true

- name: update-telemetry-collector
  plan:
    - in_parallel:
      - get: telemetry-release
      - get: ci
      - get: pivotal-telemetry-collector
        trigger: true
        params:
          unpack: true
          globs: ["*.tgz"]
      - get: bosh-cli-github-release
        params:
          globs:
          - bosh-cli-*-linux-amd64
    - task: update-release-package
      file: ci/ci/tasks/update-release-package.yml
      params:
        GCS_SERVICE_ACCOUNT_KEY: ((service-accounts/gcp.ci-gcs-service-account-key))
        GITHUB_NAME: ((telemetry-release-repo.github-name))
        GITHUB_EMAIL: ((telemetry-release-repo.github-email))
    - put: telemetry-release
      params:
        repository: telemetry-release
        rebase: true

- name: deploy-telemetry-receiver-app
  serial_groups: [telemetry-receiver, telemetry-receiver-audit]
  plan:
  - in_parallel:
    - get: telemetry-release
      resource: telemetry-receiver-source
      trigger: true
    - get: ci
  - task: test-telemetry-receiver
    file: ci/ci/tasks/run-telemetry-receiver-tests.yml
  - put: telemetry-receiver-app
    params:
      manifest: telemetry-release/src/acceptance_tests/telemetry_receiver/manifest.yml
      environment_variables:
        VALID_API_KEYS: ((telemetry-release-repo.acceptance-loader-api-keys))
        MESSAGE_LIMIT: "50"

- name: run-centralizer-unit-tests
  serial_groups: [version]
  plan:
    - get: telemetry-release
      trigger: true
    - get: version
      params: {pre: build}
    - get: ci
    - task: run-centralizer-unit-tests
      file: ci/ci/tasks/run-centralizer-unit-tests.yml
    - put: version
      params: {file: version/version}

- name: deploy-telemetry-acceptance
  serial_groups: [acceptance]
  plan:
  - in_parallel:
    - get: stemcell
    - get: bpm-release
    - get: version
      passed: [run-centralizer-unit-tests]
    - get: bosh-cli-github-release
      params:
        globs:
        - bosh-cli-*-linux-amd64
    - get: telemetry-release
      passed: [run-centralizer-unit-tests]
      trigger: true
    - get: ci
    - get: smith
      resource: smith-cli-github-release
      params:
        globs: ["*linux*"]
    - get: om
      resource: om-cli-github-release
      params:
        globs: ["*linux*"]
  - task: create-release
    file: ci/ci/tasks/create-release.yml
  - put: env-pool
    params:
      action: claim
  - task: telemetry-centralizer-acceptance-deployment
    file: ci/ci/tasks/deploy-telemetry.yml
    params:
      CENTRALIZER_DEPLOYMENT_NAME: ((telemetry-release-repo.centralizer-acceptance-deployment-name))
      AGENT_DEPLOYMENT_NAME: ((telemetry-release-repo.agent-acceptance-deployment-name))
      AUDIT_MODE: false
      LOADER_API_KEY: ((telemetry-release-repo.acceptance-loader-api-key))
      LOADER_ENDPOINT: ((telemetry-release-repo.acceptance-loader-url))
      ENV_TYPE: development
      IAAS_TYPE: ((toolsmiths/((vault-acceptance-prefix)).iaas_type))
      FOUNDATION_ID: ((toolsmiths/((vault-acceptance-prefix)).p-bosh-id-guid))
      FOUNDATION_NICKNAME: release-acceptance
      FLUSH_INTERVAL: 10
      COLLECTOR_CRON_SCHEDULE: "* * * * *"
      OPSMANAGER_HOSTNAME: ((toolsmiths/((vault-acceptance-prefix)).ops-manager-hostname))
      OPSMANAGER_CLIENT_NAME: ((toolsmiths/((vault-acceptance-prefix)).opsman-client-id))
      OPSMANAGER_CLIENT_SECRET: ((toolsmiths/((vault-acceptance-prefix)).opsman-uaa-client-secret))
      OPSMANAGER_INSECURE_SKIP_TLS_VERIFY: true
      CF_API_URL: ((toolsmiths/((vault-acceptance-prefix)).cf-api-url))
      USAGE_SERVICE_URL: ((toolsmiths/((vault-acceptance-prefix)).usage-service-url))
      USAGE_SERVICE_CLIENT_ID: ((toolsmiths/((vault-acceptance-prefix)).usage-service-client-id))
      USAGE_SERVICE_CLIENT_SECRET: ((toolsmiths/((vault-acceptance-prefix)).telemetry-usage-service-password))
      USAGE_SERVICE_INSECURE_SKIP_TLS_VERIFY: true
      TOOLSMITHS_API_TOKEN: ((toolsmiths/auth.api-token))
      DATA_COLLECTION_MULTI_SELECT_OPTIONS: '["ceip_data"]'
      OPERATIONAL_DATA_ONLY: false

- name: deploy-telemetry-acceptance-audit
  serial_groups: [acceptance-audit]
  plan:
  - in_parallel:
    - get: stemcell
    - get: bpm-release
    - get: version
      passed: [run-centralizer-unit-tests]
    - get: bosh-cli-github-release
      params:
        globs:
        - bosh-cli-*-linux-amd64
    - get: telemetry-release
      passed: [run-centralizer-unit-tests]
      trigger: true
    - get: ci
    - get: smith
      resource: smith-cli-github-release
      params:
        globs: ["*linux*"]
    - get: om
      resource: om-cli-github-release
      params:
        globs: ["*linux*"]
  - task: create-release
    file: ci/ci/tasks/create-release.yml
  - put: env-pool
    params:
      action: claim
  - task: telemetry-centralizer-acceptance-deployment
    file: ci/ci/tasks/deploy-telemetry.yml
    params:
      CENTRALIZER_DEPLOYMENT_NAME: telemetry-centralizer-acceptance-audit
      AGENT_DEPLOYMENT_NAME: telemetry-agent-acceptance-audit
      AUDIT_MODE: true
      LOADER_API_KEY: ((telemetry-release-repo.acceptance-loader-api-key-audit))
      LOADER_ENDPOINT: ((telemetry-release-repo.acceptance-loader-url))
      ENV_TYPE: development
      IAAS_TYPE: ((toolsmiths/((vault-acceptance-prefix)).iaas_type))
      FOUNDATION_ID: ((toolsmiths/((vault-acceptance-prefix)).p-bosh-id-guid))
      FOUNDATION_NICKNAME: release-acceptance
      FLUSH_INTERVAL: 10
      COLLECTOR_CRON_SCHEDULE: "* * * * *"
      OPSMANAGER_HOSTNAME: ((toolsmiths/((vault-acceptance-prefix)).ops-manager-hostname))
      OPSMANAGER_CLIENT_NAME: ((toolsmiths/((vault-acceptance-prefix)).opsman-client-id))
      OPSMANAGER_CLIENT_SECRET: ((toolsmiths/((vault-acceptance-prefix)).opsman-uaa-client-secret))
      OPSMANAGER_INSECURE_SKIP_TLS_VERIFY: true
      CF_API_URL: ((toolsmiths/((vault-acceptance-prefix)).cf-api-url))
      USAGE_SERVICE_URL: ((toolsmiths/((vault-acceptance-prefix)).usage-service-url))
      USAGE_SERVICE_CLIENT_ID: ((toolsmiths/((vault-acceptance-prefix)).usage-service-client-id))
      USAGE_SERVICE_CLIENT_SECRET: ((toolsmiths/((vault-acceptance-prefix)).telemetry-usage-service-password))
      USAGE_SERVICE_INSECURE_SKIP_TLS_VERIFY: true
      TOOLSMITHS_API_TOKEN: ((toolsmiths/auth.api-token))
      DATA_COLLECTION_MULTI_SELECT_OPTIONS: '["ceip_data"]'
      OPERATIONAL_DATA_ONLY: false

- name: test-acceptance-audit
  serial_groups: [telemetry-receiver-audit, acceptance-audit]
  plan:
  - in_parallel:
    - get: telemetry-release
      passed: [deploy-telemetry-acceptance-audit]
      trigger: true
    - get: ci
    - get: version
      passed: [deploy-telemetry-acceptance-audit]
    - get: bosh-cli-github-release
      params:
        globs:
        - bosh-cli-*-linux-amd64
    - get: smith
      resource: smith-cli-github-release
      params:
        globs: ["*linux*"]
    - get: om
      resource: om-cli-github-release
      params:
        globs: ["*linux*"]
    - get: env-pool
      passed: [deploy-telemetry-acceptance-audit]
  - task: test-acceptance-sends-to-centralizer
    attempts: 2
    file: ci/ci/tasks/test-acceptance-sends-to-centralizer.yml
    params:
      LOADER_URL: ((telemetry-release-repo.acceptance-loader-url))
      LOADER_API_KEY: ((telemetry-release-repo.acceptance-loader-api-key-audit))
      CENTRALIZER_BOSH_DEPLOYMENT: telemetry-centralizer-acceptance-audit
      AGENT_BOSH_DEPLOYMENT: telemetry-agent-acceptance-audit
      AGENT_BOSH_INSTANCE: telemetry-agent
      EXPECTED_ENV_TYPE: development
      EXPECTED_FOUNDATION_NICKNAME: release-acceptance
      EXPECTED_IAAS_TYPE: ((toolsmiths/((vault-acceptance-prefix)).iaas_type))
      EXPECTED_FOUNDATION_ID: ((toolsmiths/((vault-acceptance-prefix)).p-bosh-id-guid))
      AUDIT_MODE: true
      TOOLSMITHS_API_TOKEN: ((toolsmiths/auth.api-token))
  on_success:
    put: env-pool
    params:
      action: unclaim
      env_file: env-pool/metadata

- name: test-acceptance-sends-to-centralizer
  serial_groups: [telemetry-receiver, acceptance]
  plan:
  - in_parallel:
    - get: telemetry-release
      passed: [deploy-telemetry-acceptance]
      trigger: true
    - get: ci
    - get: version
      passed: [deploy-telemetry-acceptance]
    - get: bosh-cli-github-release
      params:
        globs:
        - bosh-cli-*-linux-amd64
    - get: smith
      resource: smith-cli-github-release
      params:
        globs: ["*linux*"]
    - get: om
      resource: om-cli-github-release
      params:
        globs: ["*linux*"]
    - get: env-pool
      passed: [deploy-telemetry-acceptance]
  - task: test-acceptance-sends-to-centralizer
    file: ci/ci/tasks/test-acceptance-sends-to-centralizer.yml
    params:
      LOADER_URL: ((telemetry-release-repo.acceptance-loader-url))
      LOADER_API_KEY: ((telemetry-release-repo.acceptance-loader-api-key))
      CENTRALIZER_BOSH_DEPLOYMENT: ((telemetry-release-repo.centralizer-acceptance-deployment-name))
      AGENT_BOSH_DEPLOYMENT: ((telemetry-release-repo.agent-acceptance-deployment-name))
      AGENT_BOSH_INSTANCE: telemetry-agent
      EXPECTED_ENV_TYPE: development
      EXPECTED_FOUNDATION_NICKNAME: release-acceptance
      EXPECTED_IAAS_TYPE: ((toolsmiths/((vault-acceptance-prefix)).iaas_type))
      EXPECTED_FOUNDATION_ID: ((toolsmiths/((vault-acceptance-prefix)).p-bosh-id-guid))
      TOOLSMITHS_API_TOKEN: ((toolsmiths/auth.api-token))
  on_success:
    put: env-pool
    params:
      action: unclaim
      env_file: env-pool/metadata

- name: deploy-telemetry-staging
  plan:
  - in_parallel:
    - get: stemcell
    - get: bpm-release
    - get: version
      passed: [test-acceptance-sends-to-centralizer]
    - get: bosh-cli-github-release
      params:
        globs:
        - bosh-cli-*-linux-amd64
    - get: telemetry-release
      passed: [test-acceptance-sends-to-centralizer]
      trigger: true
    - get: ci
    - get: smith
      resource: smith-cli-github-release
      params:
        globs: ["*linux*"]
    - get: om
      resource: om-cli-github-release
      params:
        globs: ["*linux*"]
  - task: create-release
    file: ci/ci/tasks/create-release.yml
  - task: deploy-telemetry
    file: ci/ci/tasks/deploy-telemetry.yml
    params:
      CENTRALIZER_DEPLOYMENT_NAME: telemetry-centralizer-staging
      AGENT_DEPLOYMENT_NAME: telemetry-agent-staging
      AUDIT_MODE: false
      LOADER_API_KEY: ((telemetry-release-repo.staging-loader-api-key))
      LOADER_ENDPOINT: ((telemetry-release-repo.staging-loader-endpoint))
      ENV_TYPE: development
      IAAS_TYPE: google
      FOUNDATION_ID: ((toolsmiths/((vault-staging-prefix)).p-bosh-id-guid))
      FOUNDATION_NICKNAME: release-staging
      FLUSH_INTERVAL: 10
      COLLECTOR_CRON_SCHEDULE: "0 0 * * *"
      OPSMANAGER_HOSTNAME: ((toolsmiths/((vault-acceptance-prefix)).ops-manager-hostname))
      OPSMANAGER_CLIENT_NAME: ((toolsmiths/((vault-acceptance-prefix)).opsman-client-id))
      OPSMANAGER_CLIENT_SECRET: ((toolsmiths/((vault-acceptance-prefix)).opsman-uaa-client-secret))
      OPSMANAGER_INSECURE_SKIP_TLS_VERIFY: true
      CF_API_URL: ((toolsmiths/((vault-acceptance-prefix)).cf-api-url))
      USAGE_SERVICE_URL: ((toolsmiths/((vault-acceptance-prefix)).usage-service-url))
      USAGE_SERVICE_CLIENT_ID: ((toolsmiths/((vault-acceptance-prefix)).usage-service-client-id))
      USAGE_SERVICE_CLIENT_SECRET: ((toolsmiths/((vault-acceptance-prefix)).telemetry-usage-service-password))
      USAGE_SERVICE_INSECURE_SKIP_TLS_VERIFY: true
      TOOLSMITHS_API_TOKEN: ((toolsmiths/auth.api-token))
      TOOLSMITHS_ENV: ((toolsmiths/((vault-staging-prefix)).env-name))
      DATA_COLLECTION_MULTI_SELECT_OPTIONS: '["ceip_data"]'
      OPERATIONAL_DATA_ONLY: false

- name: finalize-release
  serial_groups: [version]
  plan:
  - in_parallel:
    - get: version
      params: {bump: final}
      passed: [deploy-telemetry-staging]
    - get: bosh-cli-github-release
      params:
        globs:
        - bosh-cli-*-linux-amd64
    - get: telemetry-release
      passed: [deploy-telemetry-staging]
    - get: ci
  - task: create-final-release
    file: ci/ci/tasks/create-final-release.yml
    params:
      GCS_SERVICE_ACCOUNT_KEY: ((service-accounts/gcp.ci-gcs-service-account-key))
      GITHUB_NAME: ((telemetry-release-repo.github-name))
      GITHUB_EMAIL: ((telemetry-release-repo.github-email))
      STEMCELL_VERSION: ((stemcell-version))
  - put: telemetry-release
    params:
      branch: main
      repository: telemetry-release
      rebase: true
      tag: version/version
      tag_prefix: jammy-

- name: auto-patch
  serial_groups: [version]
  plan:
  - get: version
    passed: [finalize-release]
    params: {bump: patch, pre: build}
    trigger: true
  - put: version
    params: {file: version/version}

- name: major
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major, pre: build}
  - put: version
    params: {file: version/version}

- name: minor
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor, pre: build}
  - put: version
    params: {file: version/version}

- name: patch
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: patch, pre: build}
  - put: version
    params: {file: version/version}
