resource_types:
- name: bbl-state-resource
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cfinfrastructure/bbl-state-resource
- name: bosh-deployment
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cloudfoundry/bosh-deployment-resource
- name: pivnet
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/pivotalcf/pivnet-resource
    tag: latest-final
- name: github-release
  type: registry-image
  source: {repository: harbor-repo.vmware.com/dockerhub-proxy-cache/concourse/github-release-resource}
- name: pcf-pool
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cftoolsmiths/toolsmiths-envs-resource

resources:
- name: bosh-cli-github-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: bosh-cli
    release: true
    access_token: ((telemetry-release-github-access-token))
- name: bbl-cli-github-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: bosh-bootloader
    release: true
    access_token: ((telemetry-release-github-access-token))
- name: smith-cli-github-release
  type: github-release
  version:
    tag: 'v2.3.0'
  source:
    owner: pivotal
    repository: smith
    access_token: ((telemetry-release-github-access-token))
- name: om-cli-github-release
  type: github-release
  source:
    owner: pivotal-cf
    repository: om
    access_token: ((telemetry-release-github-access-token))
- name: telemetry-receiver-app
  type: cf
  source:
    api: ((pcf1-api-url))
    username: ((pcf1-username))
    password: ((pcf1-password))
    organization: ((pcf1-org))
    space: stage
- name: bbl-state
  type: bbl-state-resource
  source:
    bucket: ((bbl-state-bucket))
    iaas: gcp
    gcp_region: us-central1
    gcp_service_account_key: ((telemetry-release-gcp-service-account-key))
- name: xenial-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-xenial-go_agent
- name: bpm-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bpm-release
- name: telemetry-centralizer-acceptance-deployment
  type: bosh-deployment
  source:
    deployment: ((centralizer-acceptance-deployment-name))
    skip_check: true
- name: telemetry-agent-acceptance-deployment
  type: bosh-deployment
  source:
    deployment: ((agent-acceptance-deployment-name))
    skip_check: true
- name: telemetry-centralizer-acceptance-audit-deployment
  type: bosh-deployment
  source:
    deployment: ((centralizer-acceptance-audit-deployment-name))
    skip_check: true
- name: telemetry-agent-acceptance-audit-deployment
  type: bosh-deployment
  source:
    deployment: ((agent-acceptance-audit-deployment-name))
    skip_check: true
- name: telemetry-centralizer-staging-deployment
  type: bosh-deployment
  source:
    deployment: ((centralizer-staging-deployment-name))
    skip_check: true
- name: telemetry-agent-staging-deployment
  type: bosh-deployment
  source:
    deployment: ((agent-staging-deployment-name))
    skip_check: true
- name: telemetry-release
  type: git
  source:
    branch: main
    uri: git@github.com:pivotal-cf/telemetry-release
    private_key: ((telemetry-release-git-deploy-private-key))
    ignore_paths:
    - ci
- name: ci
  type: git
  source:
    branch: main
    uri: git@github.com:pivotal-cf/telemetry-release
    private_key: ((telemetry-release-git-deploy-private-key))
    paths:
    - ci
    - src
- name: telemetry-receiver-source
  type: git
  source:
    branch: main
    uri: git@github.com:pivotal-cf/telemetry-release
    paths:
    - src/acceptance_tests/telemetry_receiver
    - ci/tasks/run-telemetry-receiver-tests.*
    private_key: ((telemetry-release-git-deploy-private-key))
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:pivotal-cf/telemetry-release
    branch: version
    file: VERSION
    private_key: ((telemetry-release-git-deploy-private-key))
- name: env-pool
  type: pcf-pool
  source:
    api_token: ((toolsmiths-api-token))
    hostname: environments.toolsmiths.cf-app.com
    pool_name: us_2_10 

- name: pivotal-telemetry-collector
  type: pivnet
  source:
    api_token: {{pivnet-api-token}}
    product_slug: pivotal-telemetry-collector
    copy_metadata: true

jobs:
- name: bbl-up
  plan:
  - get: bbl-state-input
    resource: bbl-state
  - put: bbl-state
    params:
      command: up
      name: telemetry-release-bosh-director
      state_dir: bbl-state-input

- name: update-telemetry-collector
  plan:
    - in_parallel:
      - get: telemetry-release
      - get: ci
      - get: pivotal-telemetry-collector
        trigger: true
        params:
          unpack: true
          globs: ["*.tgz"]
      - get: bosh-cli-github-release
        params:
          globs:
          - bosh-cli-*-linux-amd64
    - task: update-release-package
      file: ci/ci/tasks/update-release-package.yml
      params:
        GCS_SERVICE_ACCOUNT_KEY: ((gcs-service-account-key))
        GITHUB_NAME: ((github-name))
        GITHUB_EMAIL: ((github-email))
    - put: telemetry-release
      params:
        repository: telemetry-release
        rebase: true

- name: deploy-telemetry-receiver-app
  serial_groups: [telemetry-receiver, telemetry-receiver-audit]
  plan:
  - in_parallel:
    - get: telemetry-release
      resource: telemetry-receiver-source
      trigger: true
    - get: ci
  - task: test-telemetry-receiver
    file: ci/ci/tasks/run-telemetry-receiver-tests.yml
  - put: telemetry-receiver-app
    params:
      manifest: telemetry-release/src/acceptance_tests/telemetry_receiver/manifest.yml
      environment_variables:
        VALID_API_KEYS: ((acceptance-loader-api-keys))
        MESSAGE_LIMIT: "50"

- name: run-centralizer-unit-tests
  serial_groups: [version]
  plan:
    - get: telemetry-release
      trigger: true
    - get: version
      params: {pre: build}
    - get: ci
    - task: run-centralizer-unit-tests
      file: ci/ci/tasks/run-centralizer-unit-tests.yml
    - put: version
      params: {file: version/version}

- name: deploy-telemetry-acceptance
  serial_groups: [acceptance]
  plan:
  - in_parallel:
    - get: bbl-state
      passed: [bbl-up]
    - get: xenial-stemcell
    - get: bpm-release
    - get: version
      passed: [run-centralizer-unit-tests]
    - get: bosh-cli-github-release
      params:
        globs:
        - bosh-cli-*-linux-amd64
    - get: telemetry-release
      passed: [run-centralizer-unit-tests]
      trigger: true
    - get: ci
  - task: create-release
    file: ci/ci/tasks/create-release.yml
  - put: telemetry-centralizer-acceptance-deployment
    params:
      manifest: telemetry-release/manifest/centralizer.yml
      source_file: bbl-state/bdr-source-file
      releases:
        - release-tarball/*.tgz
        - bpm-release/*.tgz
      stemcells:
        - xenial-stemcell/*.tgz
      vars:
        deployment_name: ((centralizer-acceptance-deployment-name))
        audit_mode: false
        loader_api_key: ((acceptance-loader-api-key))
        loader_endpoint: ((acceptance-loader-url))
        env_type: ((acceptance-env-type))
        iaas_type: ((acceptance-iaas-type))
        foundation_id: ((acceptance-foundation-id))
        foundation_nickname: ((acceptance-foundation-nickname))
        flush_interval: ((acceptance-centralizer-flush-interval))
        collector_cron_schedule: ((collector-cron-schedule))
        opsmanager_hostname: ((opsmanager-hostname))
        opsmanager_client_name: ((opsmanager-client-name))
        opsmanager_client_secret: ((opsmanager-client-secret))
        opsmanager_insecure_skip_tls_verify: ((opsmanager-insecure-skip-tls-verify))
        cf_api_url: ((usage-service-cf-api-url))
        usage_service_url: ((usage-service-url))
        usage_service_client_id: ((usage-service-client-id))
        usage_service_client_secret: ((usage-service-client-secret))
        usage_service_insecure_skip_tls_verify: ((usage-service-insecure-skip-tls-verify))
  - put: telemetry-agent-acceptance-deployment
    params:
      manifest: telemetry-release/manifest/agent.yml
      source_file: bbl-state/bdr-source-file
      releases:
        - release-tarball/*.tgz
        - bpm-release/*.tgz
      stemcells:
        - xenial-stemcell/*.tgz
      vars:
        agent_deployment_name: ((agent-acceptance-deployment-name))
        centralizer_deployment_name: ((centralizer-acceptance-deployment-name))

- name: deploy-telemetry-acceptance2
  serial_groups: [acceptance]
  plan:
  - in_parallel:
    - get: xenial-stemcell
    - get: bpm-release
    - get: version
      passed: [run-centralizer-unit-tests]
    - get: bosh-cli-github-release
      params:
        globs:
        - bosh-cli-*-linux-amd64
    - get: telemetry-release
      passed: [run-centralizer-unit-tests]
      trigger: true
    - get: ci
    - get: smith
      resource: smith-cli-github-release
      params:
        globs: ["*linux*"]
    - get: om
      resource: om-cli-github-release
      params:
        globs: ["*linux*"]
  - task: create-release
    file: ci/ci/tasks/create-release.yml
  - put: env-pool
    params:
      action: claim
  - task: telemetry-centralizer-acceptance-deployment
    file: ci/ci/tasks/deploy-telemetry-centralizer.yml
    params:
      DEPLOYMENT_NAME: ((centralizer-acceptance-deployment-name))
      AUDIT_MODE: false
      LOADER_API_KEY: ((acceptance-loader-api-key))
      LOADER_ENDPOINT: ((acceptance-loader-url))
      ENV_TYPE: ((acceptance-env-type))
      IAAS_TYPE: ((acceptance-iaas-type))
      FOUNDATION_ID: ((acceptance-foundation-id))
      FOUNDATION_NICKNAME: ((acceptance-foundation-nickname))
      FLUSH_INTERVAL: ((acceptance-centralizer-flush-interval))
      COLLECTOR_CRON_SCHEDULE: ((collector-cron-schedule))
      OPSMANAGER_HOSTNAME: ((opsmanager-hostname))
      OPSMANAGER_CLIENT_NAME: ((opsmanager-client-name))
      OPSMANAGER_CLIENT_SECRET: ((opsmanager-client-secret))
      OPSMANAGER_INSECURE_SKIP_TLS_VERIFY: ((opsmanager-insecure-skip-tls-verify))
      CF_API_URL: ((usage-service-cf-api-url))
      USAGE_SERVICE_URL: ((usage-service-url))
      USAGE_SERVICE_CLIENT_ID: ((usage-service-client-id))
      USAGE_SERVICE_CLIENT_SECRET: ((usage-service-client-secret))
      USAGE_SERVICE_INSECURE_SKIP_TLS_VERIFY: ((usage-service-insecure-skip-tls-verify))
      TOOLSMITHS_API_TOKEN: ((toolsmiths-api-token))
  # - task: telemetry-agent-acceptance-deployment
  #   file: ci/ci/tasks/deploy-telemetry-agent.yml
  #   params:
  #     AGENT_DEPLOYMENT_NAME: ((agent-acceptance-deployment-name))
  #     CENTRALIZER_DEPLOYMENT_NAME: ((centralizer-acceptance-deployment-name))

- name: deploy-telemetry-acceptance-audit
  serial_groups: [acceptance-audit]
  plan:
    - in_parallel:
        - get: bbl-state
          passed: [bbl-up]
        - get: xenial-stemcell
        - get: bpm-release
        - get: version
          passed: [run-centralizer-unit-tests]
        - get: bosh-cli-github-release
          params:
            globs:
              - bosh-cli-*-linux-amd64
        - get: telemetry-release
          passed: [run-centralizer-unit-tests]
          trigger: true
        - get: ci
    - task: create-release
      file: ci/ci/tasks/create-release.yml
    - put: telemetry-centralizer-acceptance-audit-deployment
      params:
        manifest: telemetry-release/manifest/centralizer.yml
        source_file: bbl-state/bdr-source-file
        releases:
          - release-tarball/*.tgz
          - bpm-release/*.tgz
        stemcells:
          - xenial-stemcell/*.tgz
        vars:
          deployment_name: ((centralizer-acceptance-audit-deployment-name))
          audit_mode: true
          loader_api_key: ((acceptance-loader-api-key-audit))
          loader_endpoint: ((acceptance-loader-url))
          env_type: ((acceptance-env-type))
          iaas_type: ((acceptance-iaas-type))
          foundation_id: ((acceptance-foundation-id))
          foundation_nickname: ((acceptance-foundation-nickname))
          flush_interval: ((acceptance-centralizer-flush-interval))
          collector_cron_schedule: ((collector-cron-schedule))
          opsmanager_hostname: ((opsmanager-hostname))
          opsmanager_client_name: ((opsmanager-client-name))
          opsmanager_client_secret: ((opsmanager-client-secret))
          opsmanager_insecure_skip_tls_verify: ((opsmanager-insecure-skip-tls-verify))
          cf_api_url: ((usage-service-cf-api-url))
          usage_service_url: ((usage-service-url))
          usage_service_client_id: ((usage-service-client-id))
          usage_service_client_secret: ((usage-service-client-secret))
          usage_service_insecure_skip_tls_verify: ((usage-service-insecure-skip-tls-verify))
    - put: telemetry-agent-acceptance-audit-deployment
      params:
        manifest: telemetry-release/manifest/agent.yml
        source_file: bbl-state/bdr-source-file
        releases:
          - release-tarball/*.tgz
          - bpm-release/*.tgz
        stemcells:
          - xenial-stemcell/*.tgz
        vars:
          agent_deployment_name: ((agent-acceptance-audit-deployment-name))
          centralizer_deployment_name: ((centralizer-acceptance-audit-deployment-name))

- name: test-acceptance-audit
  serial_groups: [telemetry-receiver-audit, acceptance-audit]
  plan:
    - in_parallel:
        - get: bbl-state
        - get: telemetry-release
          passed: [deploy-telemetry-acceptance-audit]
          trigger: true
        - get: ci
        - get: version
          passed: [deploy-telemetry-acceptance-audit]
        - get: bosh-cli-github-release
          params:
            globs:
              - bosh-cli-*-linux-amd64
        - get: bbl-cli-github-release
          params:
            globs:
              - bbl-v*_linux_x86-64
    - task: test-acceptance-audit
      file: ci/ci/tasks/test-acceptance-sends-to-centralizer.yml
      params:
        LOADER_URL: ((acceptance-loader-url))
        LOADER_API_KEY: ((acceptance-loader-api-key-audit))
        CENTRALIZER_BOSH_DEPLOYMENT: ((centralizer-acceptance-audit-deployment-name))
        AGENT_BOSH_DEPLOYMENT: ((agent-acceptance-audit-deployment-name))
        AGENT_BOSH_INSTANCE: ((agent-acceptance-instance-name))
        EXPECTED_ENV_TYPE: ((acceptance-env-type))
        EXPECTED_FOUNDATION_NICKNAME: ((acceptance-foundation-nickname))
        EXPECTED_IAAS_TYPE: ((acceptance-iaas-type))
        EXPECTED_FOUNDATION_ID: ((acceptance-foundation-id))
        AUDIT_MODE: true

- name: test-acceptance-sends-to-centralizer
  serial_groups: [telemetry-receiver, acceptance]
  plan:
  - in_parallel:
    - get: bbl-state
    - get: telemetry-release
      passed: [deploy-telemetry-acceptance]
      trigger: true
    - get: ci
    - get: version
      passed: [deploy-telemetry-acceptance]
    - get: bosh-cli-github-release
      params:
        globs:
        - bosh-cli-*-linux-amd64
    - get: bbl-cli-github-release
      params:
        globs:
        - bbl-v*_linux_x86-64
  - task: test-acceptance-sends-to-centralizer
    file: ci/ci/tasks/test-acceptance-sends-to-centralizer.yml
    params:
      LOADER_URL: ((acceptance-loader-url))
      LOADER_API_KEY: ((acceptance-loader-api-key))
      CENTRALIZER_BOSH_DEPLOYMENT: ((centralizer-acceptance-deployment-name))
      AGENT_BOSH_DEPLOYMENT: ((agent-acceptance-deployment-name))
      AGENT_BOSH_INSTANCE: ((agent-acceptance-instance-name))
      EXPECTED_ENV_TYPE: ((acceptance-env-type))
      EXPECTED_FOUNDATION_NICKNAME: ((acceptance-foundation-nickname))
      EXPECTED_IAAS_TYPE: ((acceptance-iaas-type))
      EXPECTED_FOUNDATION_ID: ((acceptance-foundation-id))

- name: deploy-telemetry-staging
  plan:
  - in_parallel:
    - get: bbl-state
      passed: [bbl-up]
    - get: xenial-stemcell
    - get: bpm-release
    - get: version
      passed: [test-acceptance-sends-to-centralizer]
    - get: bosh-cli-github-release
      params:
        globs:
        - bosh-cli-*-linux-amd64
    - get: telemetry-release
      passed: [test-acceptance-sends-to-centralizer]
      trigger: true
    - get: ci
  - task: create-release
    file: ci/ci/tasks/create-release.yml
  - put: telemetry-centralizer-staging-deployment
    params:
      manifest: telemetry-release/manifest/centralizer.yml
      source_file: bbl-state/bdr-source-file
      releases:
        - release-tarball/*.tgz
        - bpm-release/*.tgz
      stemcells:
        - xenial-stemcell/*.tgz
      vars:
        deployment_name: ((centralizer-staging-deployment-name))
        audit_mode: false
        loader_api_key: ((staging-loader-api-key))
        loader_endpoint: ((staging-loader-endpoint))
        env_type: ((staging-env-type))
        iaas_type: ((staging-iaas-type))
        foundation_id: ((staging-foundation-id))
        foundation_nickname: ((staging-foundation-nickname))
        flush_interval: ((staging-centralizer-flush-interval))
        collector_cron_schedule: "0 0 * * *"
        opsmanager_hostname: ((opsmanager-hostname))
        opsmanager_client_name: ((opsmanager-client-name))
        opsmanager_client_secret: ((opsmanager-client-secret))
        opsmanager_insecure_skip_tls_verify: ((opsmanager-insecure-skip-tls-verify))
        cf_api_url: ((usage-service-cf-api-url))
        usage_service_url: ((usage-service-url))
        usage_service_client_id: ((usage-service-client-id))
        usage_service_client_secret: ((usage-service-client-secret))
        usage_service_insecure_skip_tls_verify: ((usage-service-insecure-skip-tls-verify))
  - put: telemetry-agent-staging-deployment
    params:
      manifest: telemetry-release/manifest/agent.yml
      source_file: bbl-state/bdr-source-file
      releases:
        - release-tarball/*.tgz
        - bpm-release/*.tgz
      stemcells:
        - xenial-stemcell/*.tgz
      vars:
        agent_deployment_name: ((agent-staging-deployment-name))
        centralizer_deployment_name: ((centralizer-staging-deployment-name))
- name: finalize-release
  serial_groups: [version]
  plan:
  - in_parallel:
    - get: version
      params: {bump: final}
      passed: [deploy-telemetry-staging]
    - get: bosh-cli-github-release
      params:
        globs:
        - bosh-cli-*-linux-amd64
    - get: telemetry-release
      passed: [deploy-telemetry-staging]
    - get: ci
  - task: create-final-release
    file: ci/ci/tasks/create-final-release.yml
    params:
      GCS_SERVICE_ACCOUNT_KEY: ((gcs-service-account-key))
      GITHUB_NAME: ((github-name))
      GITHUB_EMAIL: ((github-email))
  - put: telemetry-release
    params:
      repository: telemetry-release
      tag: version/version

- name: auto-patch
  serial_groups: [version]
  plan:
  - get: version
    passed: [finalize-release]
    params: {bump: patch, pre: build}
    trigger: true
  - put: version
    params: {file: version/version}

- name: major
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major, pre: build}
  - put: version
    params: {file: version/version}

- name: minor
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor, pre: build}
  - put: version
    params: {file: version/version}

- name: patch
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: patch, pre: build}
  - put: version
    params: {file: version/version}
